import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Philosopher } from "next/font/google";

import "./globals.css";

export const metadata: Metadata = {
  title: "CAFES - AYZA",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ["200", "400", "600", "800"],
  subsets: ["latin"],
});

export const philosopher = Philosopher({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`antialiased bg-white ${poppins.className}`}>
        {children}
      </body>
    </html>
  );
}
